/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppStudiesRouteImport } from './routes/app.studies'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPacsRouteImport } from './routes/app.pacs'
import { Route as AppFreePoolRouteImport } from './routes/app.free-pool'
import { Route as AppCmsRouteImport } from './routes/app.cms'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppPacsIndexRouteImport } from './routes/app.pacs.index'
import { Route as AppBillingIndexRouteImport } from './routes/app.billing.index'
import { Route as AppStudiesStudyIdRouteImport } from './routes/app.studies.$studyId'
import { Route as AppPacsLogsRouteImport } from './routes/app.pacs.logs'
import { Route as AppPacsIngestionRouteImport } from './routes/app.pacs.ingestion'
import { Route as AppPacsEndpointsRouteImport } from './routes/app.pacs.endpoints'
import { Route as AppBillingRateCardsRouteImport } from './routes/app.billing.rate-cards'
import { Route as AppBillingPayoutsRouteImport } from './routes/app.billing.payouts'
import { Route as AppBillingInvoicesRouteImport } from './routes/app.billing.invoices'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudiesRoute = AppStudiesRouteImport.update({
  id: '/studies',
  path: '/studies',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPacsRoute = AppPacsRouteImport.update({
  id: '/pacs',
  path: '/pacs',
  getParentRoute: () => AppRoute,
} as any)
const AppFreePoolRoute = AppFreePoolRouteImport.update({
  id: '/free-pool',
  path: '/free-pool',
  getParentRoute: () => AppRoute,
} as any)
const AppCmsRoute = AppCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppPacsIndexRoute = AppPacsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPacsRoute,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppStudiesStudyIdRoute = AppStudiesStudyIdRouteImport.update({
  id: '/$studyId',
  path: '/$studyId',
  getParentRoute: () => AppStudiesRoute,
} as any)
const AppPacsLogsRoute = AppPacsLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppPacsRoute,
} as any)
const AppPacsIngestionRoute = AppPacsIngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => AppPacsRoute,
} as any)
const AppPacsEndpointsRoute = AppPacsEndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => AppPacsRoute,
} as any)
const AppBillingRateCardsRoute = AppBillingRateCardsRouteImport.update({
  id: '/rate-cards',
  path: '/rate-cards',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppBillingPayoutsRoute = AppBillingPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppBillingInvoicesRoute = AppBillingInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppBillingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/approvals': typeof AppApprovalsRoute
  '/app/billing': typeof AppBillingRouteWithChildren
  '/app/cms': typeof AppCmsRoute
  '/app/free-pool': typeof AppFreePoolRoute
  '/app/pacs': typeof AppPacsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/studies': typeof AppStudiesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/billing/invoices': typeof AppBillingInvoicesRoute
  '/app/billing/payouts': typeof AppBillingPayoutsRoute
  '/app/billing/rate-cards': typeof AppBillingRateCardsRoute
  '/app/pacs/endpoints': typeof AppPacsEndpointsRoute
  '/app/pacs/ingestion': typeof AppPacsIngestionRoute
  '/app/pacs/logs': typeof AppPacsLogsRoute
  '/app/studies/$studyId': typeof AppStudiesStudyIdRoute
  '/app/billing/': typeof AppBillingIndexRoute
  '/app/pacs/': typeof AppPacsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/cms': typeof AppCmsRoute
  '/app/free-pool': typeof AppFreePoolRoute
  '/app/reports': typeof AppReportsRoute
  '/app/studies': typeof AppStudiesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/app': typeof AppIndexRoute
  '/app/billing/invoices': typeof AppBillingInvoicesRoute
  '/app/billing/payouts': typeof AppBillingPayoutsRoute
  '/app/billing/rate-cards': typeof AppBillingRateCardsRoute
  '/app/pacs/endpoints': typeof AppPacsEndpointsRoute
  '/app/pacs/ingestion': typeof AppPacsIngestionRoute
  '/app/pacs/logs': typeof AppPacsLogsRoute
  '/app/studies/$studyId': typeof AppStudiesStudyIdRoute
  '/app/billing': typeof AppBillingIndexRoute
  '/app/pacs': typeof AppPacsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/approvals': typeof AppApprovalsRoute
  '/app/billing': typeof AppBillingRouteWithChildren
  '/app/cms': typeof AppCmsRoute
  '/app/free-pool': typeof AppFreePoolRoute
  '/app/pacs': typeof AppPacsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/studies': typeof AppStudiesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/billing/invoices': typeof AppBillingInvoicesRoute
  '/app/billing/payouts': typeof AppBillingPayoutsRoute
  '/app/billing/rate-cards': typeof AppBillingRateCardsRoute
  '/app/pacs/endpoints': typeof AppPacsEndpointsRoute
  '/app/pacs/ingestion': typeof AppPacsIngestionRoute
  '/app/pacs/logs': typeof AppPacsLogsRoute
  '/app/studies/$studyId': typeof AppStudiesStudyIdRoute
  '/app/billing/': typeof AppBillingIndexRoute
  '/app/pacs/': typeof AppPacsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/approvals'
    | '/app/billing'
    | '/app/cms'
    | '/app/free-pool'
    | '/app/pacs'
    | '/app/reports'
    | '/app/studies'
    | '/auth/callback'
    | '/app/'
    | '/app/billing/invoices'
    | '/app/billing/payouts'
    | '/app/billing/rate-cards'
    | '/app/pacs/endpoints'
    | '/app/pacs/ingestion'
    | '/app/pacs/logs'
    | '/app/studies/$studyId'
    | '/app/billing/'
    | '/app/pacs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/approvals'
    | '/app/cms'
    | '/app/free-pool'
    | '/app/reports'
    | '/app/studies'
    | '/auth/callback'
    | '/app'
    | '/app/billing/invoices'
    | '/app/billing/payouts'
    | '/app/billing/rate-cards'
    | '/app/pacs/endpoints'
    | '/app/pacs/ingestion'
    | '/app/pacs/logs'
    | '/app/studies/$studyId'
    | '/app/billing'
    | '/app/pacs'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/approvals'
    | '/app/billing'
    | '/app/cms'
    | '/app/free-pool'
    | '/app/pacs'
    | '/app/reports'
    | '/app/studies'
    | '/auth/callback'
    | '/app/'
    | '/app/billing/invoices'
    | '/app/billing/payouts'
    | '/app/billing/rate-cards'
    | '/app/pacs/endpoints'
    | '/app/pacs/ingestion'
    | '/app/pacs/logs'
    | '/app/studies/$studyId'
    | '/app/billing/'
    | '/app/pacs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/studies': {
      id: '/app/studies'
      path: '/studies'
      fullPath: '/app/studies'
      preLoaderRoute: typeof AppStudiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pacs': {
      id: '/app/pacs'
      path: '/pacs'
      fullPath: '/app/pacs'
      preLoaderRoute: typeof AppPacsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/free-pool': {
      id: '/app/free-pool'
      path: '/free-pool'
      fullPath: '/app/free-pool'
      preLoaderRoute: typeof AppFreePoolRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cms': {
      id: '/app/cms'
      path: '/cms'
      fullPath: '/app/cms'
      preLoaderRoute: typeof AppCmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pacs/': {
      id: '/app/pacs/'
      path: '/'
      fullPath: '/app/pacs/'
      preLoaderRoute: typeof AppPacsIndexRouteImport
      parentRoute: typeof AppPacsRoute
    }
    '/app/billing/': {
      id: '/app/billing/'
      path: '/'
      fullPath: '/app/billing/'
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/app/studies/$studyId': {
      id: '/app/studies/$studyId'
      path: '/$studyId'
      fullPath: '/app/studies/$studyId'
      preLoaderRoute: typeof AppStudiesStudyIdRouteImport
      parentRoute: typeof AppStudiesRoute
    }
    '/app/pacs/logs': {
      id: '/app/pacs/logs'
      path: '/logs'
      fullPath: '/app/pacs/logs'
      preLoaderRoute: typeof AppPacsLogsRouteImport
      parentRoute: typeof AppPacsRoute
    }
    '/app/pacs/ingestion': {
      id: '/app/pacs/ingestion'
      path: '/ingestion'
      fullPath: '/app/pacs/ingestion'
      preLoaderRoute: typeof AppPacsIngestionRouteImport
      parentRoute: typeof AppPacsRoute
    }
    '/app/pacs/endpoints': {
      id: '/app/pacs/endpoints'
      path: '/endpoints'
      fullPath: '/app/pacs/endpoints'
      preLoaderRoute: typeof AppPacsEndpointsRouteImport
      parentRoute: typeof AppPacsRoute
    }
    '/app/billing/rate-cards': {
      id: '/app/billing/rate-cards'
      path: '/rate-cards'
      fullPath: '/app/billing/rate-cards'
      preLoaderRoute: typeof AppBillingRateCardsRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/app/billing/payouts': {
      id: '/app/billing/payouts'
      path: '/payouts'
      fullPath: '/app/billing/payouts'
      preLoaderRoute: typeof AppBillingPayoutsRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/app/billing/invoices': {
      id: '/app/billing/invoices'
      path: '/invoices'
      fullPath: '/app/billing/invoices'
      preLoaderRoute: typeof AppBillingInvoicesRouteImport
      parentRoute: typeof AppBillingRoute
    }
  }
}

interface AppBillingRouteChildren {
  AppBillingInvoicesRoute: typeof AppBillingInvoicesRoute
  AppBillingPayoutsRoute: typeof AppBillingPayoutsRoute
  AppBillingRateCardsRoute: typeof AppBillingRateCardsRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
}

const AppBillingRouteChildren: AppBillingRouteChildren = {
  AppBillingInvoicesRoute: AppBillingInvoicesRoute,
  AppBillingPayoutsRoute: AppBillingPayoutsRoute,
  AppBillingRateCardsRoute: AppBillingRateCardsRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
}

const AppBillingRouteWithChildren = AppBillingRoute._addFileChildren(
  AppBillingRouteChildren,
)

interface AppPacsRouteChildren {
  AppPacsEndpointsRoute: typeof AppPacsEndpointsRoute
  AppPacsIngestionRoute: typeof AppPacsIngestionRoute
  AppPacsLogsRoute: typeof AppPacsLogsRoute
  AppPacsIndexRoute: typeof AppPacsIndexRoute
}

const AppPacsRouteChildren: AppPacsRouteChildren = {
  AppPacsEndpointsRoute: AppPacsEndpointsRoute,
  AppPacsIngestionRoute: AppPacsIngestionRoute,
  AppPacsLogsRoute: AppPacsLogsRoute,
  AppPacsIndexRoute: AppPacsIndexRoute,
}

const AppPacsRouteWithChildren =
  AppPacsRoute._addFileChildren(AppPacsRouteChildren)

interface AppStudiesRouteChildren {
  AppStudiesStudyIdRoute: typeof AppStudiesStudyIdRoute
}

const AppStudiesRouteChildren: AppStudiesRouteChildren = {
  AppStudiesStudyIdRoute: AppStudiesStudyIdRoute,
}

const AppStudiesRouteWithChildren = AppStudiesRoute._addFileChildren(
  AppStudiesRouteChildren,
)

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppBillingRoute: typeof AppBillingRouteWithChildren
  AppCmsRoute: typeof AppCmsRoute
  AppFreePoolRoute: typeof AppFreePoolRoute
  AppPacsRoute: typeof AppPacsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppStudiesRoute: typeof AppStudiesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppBillingRoute: AppBillingRouteWithChildren,
  AppCmsRoute: AppCmsRoute,
  AppFreePoolRoute: AppFreePoolRoute,
  AppPacsRoute: AppPacsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppStudiesRoute: AppStudiesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
